# Generated by Django 4.0.4 on 2022-05-31 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_app', '0002_category_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
