# Generated by Django 4.0.4 on 2022-06-01 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense_app', '0006_incomecategory_income'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IncomeCategory',
            new_name='Source',
        ),
        migrations.RenameField(
            model_name='income',
            old_name='category',
            new_name='source',
        ),
    ]
